### PR TITLE
Fix regexp escaping and docker signals handling for logstash process

### PR DESCRIPTION
**Pull request by ediskandarov-cur**

### CODE REVIEW

**Comment by vaijab** [comment]
I don't think that curly braces need to be escaped in regex. What is the issue you're having escaping fixes?

**Comment by ediskandarov-cur** [comment]
regexp optimization/fix.
`{` is a special symbol in many dialects. Is logstash an exception? `/^{.*}$/`

**Comment by ediskandarov-cur** [comment]
And another question:
`/var/log/containers/*.log` can contain only content generated by json logging docker's engine.
Why do we need to check if input is a json formatted string?

```
filter {
  if "kubernetes" and "docker" in [tags] {
    # check if message looks like json and try to decode it
    if [message] =~ /^\{.*\}$/ {
      json {
        source => "message"
        target => "message"
        remove_field => [ "[message][stream]" ]
      }
```

**Comment by ediskandarov-cur** [comment]
It looks like in our installation logstash spend cpu cycles on regex parsing

**Comment by vaijab** [comment]
@toidi I think you're right about escaping in this case, because of java:

http://www.regular-expressions.info/characters.html

> Most regular expression flavors treat the brace { as a literal character, unless it is part of a repetition
> operator like a{1,3}. So you generally do not need to escape it with a backslash, though you can do so if you want. An exception to this rule is the Java, which requires all literal braces to be escaped.

**Comment by vaijab** [comment]
> Why do we need to check if input is a json formatted string?

True, we don't have to.

**Comment by ediskandarov-cur** [comment]
Ok. Will you merge it? I'll create another PR to remove redundant regex matching.

**Comment by ediskandarov-cur** [comment]
however logstash might have another semantics rather than java.
It might makes sense not to escape.

**Comment by ediskandarov-cur** [comment]
those patterns doesn't fall into repetition category.

**Comment by vaijab** [comment]
> It might makes sense not to escape.

As far as I know escaping does not hurt. So let's escape it.

**Comment by vaijab** [comment]
Could you clean up your commits and I will merge.

**Comment by ediskandarov-cur** [comment]
done

**Pull request merged**
