### PR TITLE
add logstash DaemonSet kube specification

### PR DESCRIPTION
**Pull request by ediskandarov-cur**

### CODE REVIEW

**Comment by ediskandarov-cur** [comment]
BTW. It looks like my cluster issues were related to regex matching.

**Comment by ediskandarov-cur** [comment]
Hey @vaijab! Are you interested in this PR?

**Comment by vaijab** [comment]
@toidi since this is just an example and I have never run logstash as a daemonset, I'll leave this open. It's on my todo list to move a lot of things from fleet to daemonsets, so I'll come back to this hopefully soon. Thanks anyway!

**Comment by ediskandarov-cur** [comment]
of course. Anyway it worked for me and I wanted to share this spec.

**Pull request closed without merging**
