### PR TITLE
Adding initial working bits

### PR DESCRIPTION
**Pull request by vaijab**

### CODE REVIEW

**Comment by gambol99** [comment]
LGTM :+1:

**Comment by jon-shanks** [comment]
I think the docs could do with a bit more explanation if possible or maybe nice links to other bits your'e referring too i.e. the logstash kubernetes metadata support

**Comment by vaijab** [comment]
@jon-shanks sure, I was not very clear. See updated docs.

**Comment by vaijab** [comment]
@jon-shanks sure, please see updated README.

**Comment by jon-shanks** [comment]
Great. Looks good.

**Pull request merged**
