### PR TITLE
Add http compression

### PR DESCRIPTION
**Pull request by marcinc**

### CODE REVIEW

**Review by KashifSaadat — APPROVED** [review]
LGTM

**Review by jits — APPROVED** [review]
LG

Worth making that configurable via an env var?

**Comment by marcinc** [comment]
@jits Nah, I think we should always compress bulk requests. ES automatically compresses responses already. This option was somehow overlooked when migrating from earlier versions.

**Review by KashifSaadat — APPROVED** [review]
LG

**Pull request merged**
