### PR TITLE
add options for logstash command line arguments

### LINKED ISSUE #19: High CPU utilization and crash
The following error happens every 5 mins

```
ger.go:2047] Back-off 5m0s restarting failed container=logstash-elasticsearch pod=logstash-elasticsearch-ip-172-31-17-44.ap-southeast-1.compute.internal_kube-system(0db8a365b1
workers.go:138] Error syncing pod 0db8a365b146ec82e785690c2311079b, skipping: failed to "StartContainer" for "logstash-elasticsearch" with CrashLoopBackOff: "Back-off 5m0s res
t.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"logstash-elasticsearch-ip-172-31-17-44.ap-so
t.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"logstash-elasticsearch-ip-172-31-17-44.ap-so
ger.go:2047] Back-off 5m0s restarting failed container=logstash-elasticsearch pod=logstash-elasticsearch-ip-172-31-17-44.ap-southeast-1.compute.internal_kube-system(0db8a365b1
workers.go:138] Error syncing pod 0db8a365b146ec82e785690c2311079b, skipping: failed to "StartContainer" for "logstash-elasticsearch" with CrashLoopBackOff: "Back-off 5m0s res
t.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"logstash-elasticsearch-ip-172-31-17-44.ap-so
t.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"logstash-elasticsearch-ip-172-31-17-44.ap-so
ger.go:2047] Back-off 5m0s restarting failed container=logstash-elasticsearch pod=logstash-elasticsearch-ip-172-31-17-44.ap-southeast-1.compute.internal_kube-system(0db8a365b1
workers.go:138] Error syncing pod 0db8a365b146ec82e785690c2311079b, skipping: failed to "StartContainer" for "logstash-elasticsearch" with CrashLoopBackOff: "Back-off 5m0s res
t.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"logstash-elasticsearch-ip-172-31-17-44.ap-so
t.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"logstash-elasticsearch-ip-172-31-17-44.ap-so
```

when container starts - `top` shows the following picture
java

### PR DESCRIPTION
**Pull request by ediskandarov-cur**
Possibly will fix #19

### CODE REVIEW

**Comment by vaijab** [comment]
I think it makes more sense to just allow `${LOGSTASH_ARGS}` to be specified rather than separate environment variables for each argument. Can you change that?

**Comment by ediskandarov-cur** [comment]
Yes I can

**Comment by ediskandarov-cur** [comment]
@vaijab, I updated PR

**Comment by vaijab** [comment]
Brilliant. Thanks!

**Pull request merged**
